version: '3'
services:
  chatlang-dev: 
    image: registry.digitalocean.com/kubishi-registry/chatlang:latest
    build: .
    environment:
      - PREFIX=/chatlang
    volumes:
      - .env:/app/.env
    ports:
      - "5000:5000"
    # command: gunicorn --bind 0.0.0.0:5000 app:app
    command: python app.py
