version: '3'
services:
  chatlang-dev: 
    image: jaredraycoleman/chatlang:latest
    build: .
    environment:
      - PREFIX=/chatlang
      - ENABLE_GITHUB_LOGIN=true
    volumes:
      - .env:/app/.env
    ports:
      - "5000:5000"
    command: gunicorn --bind 0.0.0.0:5000 server:app
