version: '3'
services:
  chatlang:
    image: jaredraycoleman/chatlang:latest
    build: .
    networks:
      - traefik_proxy
    environment:
      - PREFIX=/chatlang
      - FLASK_ENV=production
      - REDIS_URL=redis://redis:6379/0 # Add this line
    volumes:
      - .env:/app/.env
    command: gunicorn --bind 0.0.0.0:5000 --env FLASK_ENV=production --env PREFIX=/chatlang app:app
    # command: python app.py
    deploy:
      labels:
        - "traefik.port=5000"
        - "traefik.backend=chatlang"
        - "traefik.frontend.rule=PathPrefix:/chatlang"
      placement:
        constraints:
          - node.role == manager

  redis: # Add this service
    image: redis:latest
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
